sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  #   via the "travis encrypt" command using the project repo's public key
  - secure: "ZPVIqS6exYthp6FL6XQYyzz3Y17BKUP60bMj3X6vHk0aJ3d5jOVE4OEOjEY2uOnEWQej1a1ea0kBqpvljnrDUNZZjKdG7Auv0N8Dmg1RKznyjHLbqoGPD2Yj+ooYHT8qE7thCZC8v7axoCf2sObViWtZg3AmeqAMVxHGoG3OxRU="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
  coverity_scan:
    project:
      name: "sekrit-twc/zimg"
      description: "Build submitted via Travis CI"
    notification_email: noreply@example.com
    build_command_prepend: "autoreconf -i && ./configure --enable-x86simd --enable-testapp --enable-examples; make clean"
    build_command: "make"
    branch_pattern: coverity_scan
script:
  - ./autogen.sh
  - ./configure --enable-x86simd --enable-testapp --enable-example --enable-unit-test
  - make clean
  - make
  - make test/unit_test
  - ./test/unit_test
